### ISSUE TITLE
源码中计算跳跃高度的公式有些小疑问

### ISSUE THREAD

**Issue by licongmu** [keenwon/flappy-pig#1]
竖直上抛的公式vt-(1/2)gt^2，但是我在源码中看到你使用的公式是vt-2gt^2，这是为什么呢？

**Comment by keenwon** [comment]
我记得是因为用1/2的话，跳的太低了，所以修改了下。http://keenwon.com/973.html 这里解释了

**Comment by licongmu** [comment]
所噶，源码写的很清晰，读起来非常舒服
