### ISSUE TITLE
拿你的游戏源码作为博客分析文啦~

### ISSUE THREAD

**Issue by licongmu** [keenwon/flappy-pig#2]
写博客的时候对源码中有一个地方有些小小的费解，源码中pig.js中添加监听函数是这么写的：
t._addListener(overCallback);
 _addListener: function (overCallback) {
            this._overCallback = overCallback;
        }
为什么不直接写成t._overCallback = overCallback呢，感觉这里是不是有些多余了呢？

**Comment by licongmu** [comment]
源码分析地址是 http://www.cnblogs.com/A-dam/
作者大大可以监督我写的怎么样哈哈哈。

**Comment by keenwon** [comment]
这个无所谓，看你怎么理解了，每个组件都是一个对象，初始化的时候执行`init`方法。而`init`只是个入口，里面会执行更多的初始化方法，例如这里的添加监听。如果所有初始化方法都直接写在init里的话，第一逻辑复杂的时候`init`会很臃肿；第二不方便复用。

**Comment by licongmu** [comment]
嗯我尊重你的写法，所以向原作者大大确认一下XD
